/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.Controller;
import java.util.List;
import model.Player;
import model.SortedListModel;

/**
 *
 * @author djani
 */
public class ScorePanel extends javax.swing.JPanel {

    Controller controller;
    SortedListModel<Player> playerModel = new SortedListModel<>();
    boolean connected;

    
    /**
     * Creates new form ScorePanel
     */
    public ScorePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtPlayerName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstPlayers = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTimeSurvived = new javax.swing.JLabel();
        helpButton = new javax.swing.JButton();
        btnConnect = new javax.swing.JButton();
        btnStartGame = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(230, 700));

        jLabel1.setText("Player Name:");

        txtPlayerName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtPlayerName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtPlayerName.setText("Anonymous");

        lstPlayers.setEnabled(false);
        jScrollPane1.setViewportView(lstPlayers);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Scoreboard:");

        jLabel3.setText("Time Survived:");

        txtTimeSurvived.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtTimeSurvived.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTimeSurvived.setText("Time");

        helpButton.setText("?");
        helpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpButtonActionPerformed(evt);
            }
        });

        btnConnect.setText("Click here to connect!");
        btnConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnectActionPerformed(evt);
            }
        });

        btnStartGame.setText("Start Game");
        btnStartGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartGameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(helpButton)
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnStartGame, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnConnect, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTimeSurvived, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addComponent(txtPlayerName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(22, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(helpButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPlayerName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtTimeSurvived, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnConnect)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnStartGame)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void helpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpButtonActionPerformed
        if (controller != null) {
            controller.displayHelpDialog();
            controller.focusOnPanel();
        }
    }//GEN-LAST:event_helpButtonActionPerformed

    private void btnConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnectActionPerformed
        if (controller != null) {
            if(!connected) {
                controller.establishConnection();
            } else {
                controller.loadPlayerScores();
            }
            controller.focusOnPanel();
        }
        
    }//GEN-LAST:event_btnConnectActionPerformed

    private void btnStartGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartGameActionPerformed
        if (controller != null) {
            controller.startGame();
            controller.focusOnPanel();
        }
    }//GEN-LAST:event_btnStartGameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConnect;
    private javax.swing.JButton btnStartGame;
    private javax.swing.JButton helpButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstPlayers;
    private javax.swing.JLabel txtPlayerName;
    private javax.swing.JLabel txtTimeSurvived;
    // End of variables declaration//GEN-END:variables

    public void setController(Controller controller) {
        this.controller = controller;
    }

    public void setPlayerName(String name) {
        txtPlayerName.setText(name);
    }

    public void setTimeSurvived(int time) {
        txtTimeSurvived.setText(time/1000 + " sec");
    }
    
    public void setConnected(boolean connected) {
        this.connected = connected;
        btnConnect.setEnabled(!connected);
        lstPlayers.setEnabled(connected);
        if(connected) {
            btnConnect.setText("Connected!");
        } else {
            btnConnect.setText("Click here to connect!");
        }
    }
    
    public void addPlayers(List<Player> players) {
        for (Player player : players) {
            playerModel.addElement(player, true);
        }
        lstPlayers.setModel(playerModel);
    }

    public void clearAllPlayers() {
        playerModel = new SortedListModel<>();
    }
    
    public void setStartGameBtnActive(boolean active) {
        btnStartGame.setEnabled(active);
        if(active) {
            btnStartGame.setText("Start Game");
        } else {
            btnStartGame.setText("Game Started");
        }
    }
    
}
